# Note, this code use NatGateway instead of NatInstance.
# Its much simpler and reliable structure, but its not free tier
# http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/vpc-nat-comparison.html
#
# NatGateway start charges immediately when its turn on. ~ ($0.045 per hour)
# For more detail refer, https://aws.amazon.com/vpc/pricing/
#
---
AWSTemplateFormatVersion: 2010-09-09
Description: This template creates an RDS database with Mysql engine
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: Export VPC Stack Name
        Parameters:
          - ExportVpcStackName
      - Label:
          default: Database Parameters
        Parameters:
          - DatabaseInstanceIdentifier
          - DatabaseName
          - DatabaseUser
          - DatabasePassword
          - DatabaseBackupRetentionPeriod
          - DatabaseAllocatedStorage
          - DatabaseInstanceClass
          - MultiAZDatabase
Parameters:
  ExportVpcStackName:
    Description: The name of the vpc stack that exports values
    Type: String
  InsertPrivateSubnetId01:
    Description: Private SubnetId for Database
    Type: String
  InsertPrivateSubnetId02:
    Description: Private SubnetId for Database
    Type: String
  DatabaseInstanceIdentifier:
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: Must begin with letter and contain only alphabet
    Default: mysqldb
    Description: Instance identifier name
    MaxLength: 60
    MinLength: 1
    Type: String
  DatabaseName:
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: Must begin with letter and contain only alphabet
    Default: testdb
    Description: Mysql database name
    MaxLength: 64
    MinLength: 1
    Type: String
  DatabaseUser:
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: Must begin with letter and contain only alphabet
    Default: test
    Description: Username for Mysql database access
    MaxLength: 16
    MinLength: 1
    NoEcho: true
    Type: String
  DatabasePassword:
    AllowedPattern: '[a-zA-Z0-9]*'
    ConstraintDescription: Must contain only alphanumeric characters
    Default: test1234
    Description: Password for Mysql database access
    MaxLength: 41
    MinLength: 8
    NoEcho: true
    Type: String
  DatabaseBackupRetentionPeriod:
    ConstraintDescription: Database backup retention period must be between 0 and 35
    Default: 0
    Description: The number of days for which automatic DB snapshots are retained
    MaxLength: 35
    MinLength: 0
    Type: String
  DatabaseAllocatedStorage:
    ConstraintDescription: Must be between 5 and 1024Gb
    Default: 20
    Description: The size of the database (Gb)
    MaxValue: 1024
    MinValue: 5
    Type: Number
  DatabaseInstanceClass:
    AllowedValues:
      - db.t1.micro
      - db.t2.micro
      - db.m1.small
      - db.m1.medium
      - db.m1.large
    ConstraintDescription: Must select a valid database instance type
    Default: db.t2.micro
    Description: The database instance type
    Type: String
  MultiAZDatabase:
    AllowedValues:
      - true
      - false
    ConstraintDescription: Must be either true of false
    Default: false
    Description: Creates a Multi MySQL Amazon RDS database instance
    Type: String
Resources:
  DatabaseSubnetGroup:
    Type: 'AWS::RDS::DBSubnetGroup'
    Properties:
      DBSubnetGroupDescription: Subnet group for RDS database
      SubnetIds:
        - !Ref InsertPrivateSubnetId01
        - !Ref InsertPrivateSubnetId02
      Tags:
        - Key: Name
          Value: database subnet
  DatabaseInstance:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      AllocatedStorage: !Ref DatabaseAllocatedStorage
      AvailabilityZone: !Select 
        - 0
        - !GetAZs ''
      BackupRetentionPeriod: !Ref DatabaseBackupRetentionPeriod
      DBInstanceClass: !Ref DatabaseInstanceClass
      DBInstanceIdentifier: !Ref DatabaseInstanceIdentifier
      DBName: !Ref DatabaseName
      DBSubnetGroupName: !Ref DatabaseSubnetGroup
      Engine: MySQL
      EngineVersion: 8.0.32
      MasterUsername: !Ref DatabaseUser
      MasterUserPassword: !Ref DatabasePassword
      MultiAZ: !Ref MultiAZDatabase
